using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace ClientService
{
  public enum TCPGameServerCmds
  {
    CMD_LOGIN_ON1 = 1,
    CMD_LOGIN_ON2 = 20,
    CMD_LOGIN_ON = 100,
    CMD_ROLE_LIST, CMD_CREATE_ROLE, CMD_REMOVE_ROLE,
    CMD_INIT_GAME, CMD_SYNC_TIME, CMD_PLAY_GAME, CMD_SPR_MOVE, CMD_SPR_MOVEEND, CMD_SPR_MOVE2,
    CMD_OTHER_ROLE, CMD_OTHER_ROLE_DATA, CMD_SPR_POSITION, CMD_SPR_PETPOS, CMD_SPR_ACTTION, CMD_SPR_ACTTION2,
    CMD_SPR_MAGICCODE, CMD_SPR_ATTACK, CMD_SPR_INJURE,
    CMD_SPR_REALIVE, CMD_SPR_RELIFE, CMD_SPR_CLICKON, CMD_SYSTEM_MONSTER,
    CMD_SPR_MAPCHANGE, CMD_LOG_OUT, CMD_SPR_NEWTASK, CMD_SPR_GETATTRIB2,
    CMD_SPR_LEAVE, CMD_SPR_NPC_BUY, CMD_SPR_NPC_SALEOUT, CMD_SPR_ADD_GOODS, CMD_SPR_MOD_GOODS,
    CMD_SPR_MERGE_GOODS, CMD_SPR_SPLIT_GOODS, CMD_SPR_GET_MERGETYPES, CMD_SPR_GET_MERGEITEMS, CMD_SPR_GET_MERGENEWGOODS,
    CMD_SPR_CHGCODE, CMD_SPR_MONEYCHANGE, CMD_SPR_MODTASK, CMD_SPR_COMPTASK, CMD_SPR_EXPCHANGE,
    CMD_SPR_GETFRIENDS, CMD_SPR_ADDFRIEND, CMD_SPR_REMOVEFRIEND,
    CMD_SPR_NEWGOODSPACK, CMD_SPR_DELGOODSPACK, CMD_SPR_CLICKONGOODSPACK,
    CMD_SPR_GETTHING, CMD_SPR_CHGPKMODE, CMD_SPR_CHGPKVAL, CMD_SPR_UPDATENPCSTATE, CMD_SPR_NPCSTATELIST, CMD_SPR_GETNEWTASKDATA,
    CMD_SPR_ABANDONTASK, CMD_SPR_HITED, CMD_SPR_MODKEYS, CMD_SPR_CHAT,
    CMD_SPR_USEGOODS, CMD_SPR_CHANGEPOS, CMD_SPR_NOTIFYCHGMAP, CMD_SPR_FORGE, CMD_SPR_ENCHANCE,
    CMD_SPR_GETOTHERATTRIB, CMD_SPR_UPDATE_ROLEDATA, CMD_SPR_REMOVE_COOLDOWN,
    CMD_SPR_MALL_BUY, CMD_SPR_YINLIANG_BUY, CMD_SPR_USERMONEYCHANGE, CMD_SPR_USERYINLIANGCHANGE, CMD_SPR_GOODSEXCHANGE, CMD_SPR_EXCHANGEDATA,
    CMD_SPR_MOVEGOODSDATA, CMD_SPR_GOODSSTALL, CMD_SPR_STALLDATA, CMD_SPR_STALLNAME,
    CMD_SPR_TEAM, CMD_SPR_TEAMDATA, CMD_SPR_TEAMID, CMD_SPR_BATTLE, CMD_SPR_NPCSCRIPT,
    CMD_SPR_DEAD, CMD_SPR_AUTOFIGHT, CMD_SPR_HORSE, CMD_SPR_PET,
    CMD_SPR_DIANJIANGLIST, CMD_SPR_DIANJIANGDATA, CMD_SPR_DJROOMROLESDATA, CMD_SPR_DIANJIANG, CMD_SPR_DIANJIANGFIGHT,
    CMD_SPR_DIANJIANGPOINT, CMD_SPR_GETDJPOINTS, CMD_SPR_UPDATEINTERPOWER,
    CMD_SPR_GOTOMAP, CMD_SPR_NOTIFYMSG, CMD_SPR_QUERYIDBYNAME, CMD_ADDHORSE, CMD_ADDPET, CMD_GETHORSELIST, CMD_GETOTHERHORSELIST, CMD_GETPETLIST,
    CMD_MODHORSE, CMD_MODPET, CMD_SELECTHORSE, CMD_GETGOODSLISTBYSITE, CMD_GETLINEINFO, CMD_GETJINGMAILIST, CMD_UP_JINGMAI_LEVEL,
    CMD_GETOTHERJINGMAILIST, CMD_SPR_LOADALREADY, CMD_SPR_BULLETINMSG, CMD_SPR_GMAUTH, CMD_SPR_EQUIPUPGRADE, CMD_SPR_ENCHASEJEWEL,
    CMD_SPR_SHOWBIGUAN, CMD_SPR_GETBIGUAN, CMD_SPR_UPSKILLLEVEL, CMD_SPR_ADD_SKILL, CMD_SPR_JINGMAI_INFO, CMD_SPR_HORSEENCHANCE,
    CMD_SPR_HORSEUPGRADE, CMD_SPR_SALEGOODS, CMD_SPR_SELFSALEGOODSLIST, CMD_SPR_OTHERSALEGOODSLIST, CMD_SPR_MARKETROLELIST,
    CMD_SPR_MARKETGOODSLIST, CMD_SPR_MARKETBUYGOODS, CMD_SPR_MODDEFSKILLID, CMD_SPR_MODAUTODRINK, CMD_SPR_PLAYDECO, CMD_SPR_BUFFERDATA,
    CMD_SPR_RUNTOMAP, CMD_SPR_SEARCHROLES, CMD_SPR_LISTROLES, CMD_SPR_LISTTEAMS, CMD_SPR_RESETBAG, CMD_SPR_DAILYTASKDATA, CMD_SPR_DAILYJINGMAIDATA,
    CMD_SPR_CHGNUMSKILLID, CMD_SPR_GETSKILLUSEDNUM, CMD_SPR_CHGHORSEBODY, CMD_SPR_PORTABLEBAGDATA, CMD_SPR_RESETPORTABLEBAG,
    CMD_SPR_EXECWABAO, CMD_SPR_GETWABAODATA, CMD_SPR_GETHUODONGDATA, CMD_SPR_GETWLOGINGIFT, CMD_SPR_GETNEWSTEPGIFT, CMD_SPR_GETMTIMEGIFT,
    CMD_SPR_GETBIGGIFT, CMD_SPR_GETSONGLIGIFT, CMD_SPR_CHGHUODONGID, CMD_SPR_FUBENDATA, CMD_SPR_ENTERFUBEN, CMD_SPR_NOTIFYENTERFUBEN,
    CMD_SPR_CLIENTHEART, CMD_SPR_OHTERJINGMAIEXP, CMD_GETRANDOMNAME, CMD_SKILLUSEDNUMFULL, CMD_SPR_GETFUBENHISTDATA, CMD_SPR_GETFUBENBEGININFO,
    CMD_SPR_COPYMAPMONSTERSNUM, CMD_SPR_FINDMONSTER, CMD_SPR_BATCHYINPIAO, CMD_SPR_FORCETOLAOFANG, CMD_SPR_CHGPURPLENAME, CMD_SPR_CHGLIANZHAN,
    CMD_SPR_GETROLEDAILYDATA, CMD_SPR_GETBOSSINFODICT, CMD_SPR_GETPAIHANGLIST, CMD_SPR_YABIAODATA, CMD_SPR_STARTYABIAO, CMD_SPR_ENDYABIAO,
    CMD_SPR_YABIAOTAKEGOODS, CMD_SPR_TOUBAO, CMD_SPR_GETOTHERATTRIB2, CMD_SPR_NEWBIAOCHE, CMD_SPR_DELBIAOCHE, CMD_SPR_FINDBIAOCHE,
    CMD_SPR_CHGBIAOCHELIFEV, CMD_SPR_NOTIFYENDCHONGXUE, CMD_SPR_ADDHORSELUCKY, CMD_SPR_BATTLEKILLEDNUM, CMD_SPR_CHGBATTLENAMEINFO,
    CMD_SPR_NOFITYPOPUPWIN, CMD_SPR_NOTIFYBATTLEROLEINFO, CMD_SPR_NOTIFYBATTLEENDINFO, CMD_SPR_GETCHONGZHIJIFEN, CMD_SPR_NOTIFYTEAMCHGLEVEL,
    CMD_SPR_GETFUBENHISTLISTDATA, CMD_SPR_CHGHEROINDEX, CMD_GETOTHERHORSEDATA, CMD_UPDATEALLTHINGINDEXS, CMD_SPR_CHGHALFYINLIANGPERIOD,
    CMD_SPR_GETBANGHUILIST, CMD_SPR_CREATEBANGHUI, CMD_SPR_CHGBANGHUIINFO, CMD_SPR_QUERYBANGHUIDETAIL, CMD_SPR_UPDATEBANGHUIBULLETIN,
    CMD_SPR_GETBHMEMBERDATALIST, CMD_SPR_UPDATEBHVERIFY, CMD_SPR_APPLYTOBHMEMBER, CMD_SPR_ADDBHMEMBER, CMD_SPR_REMOVEBHMEMBER,
    CMD_SPR_QUITFROMBANGHUI, CMD_SPR_DESTROYBANGHUI, CMD_SPR_BANGHUIVERIFY, CMD_SPR_INVITETOBANGHUI, CMD_SPR_CHGBHMEMBERZHIWU,
    CMD_SPR_CHGBHMEMBERCHENGHAO, CMD_SPR_SEARCHROLESFROMDB, CMD_SPR_AGREETOTOBANGHUI, CMD_SPR_REFUSEAPPLYTOBH, CMD_SPR_GETBANGGONGHIST,
    CMD_SPR_DONATEBGMONEY, CMD_SPR_DONATEBGGOODS, CMD_SPR_BANGGONGCHANGE, CMD_SPR_GETBANGQIINFO, CMD_SPR_RENAMEBANGQI, CMD_SPR_UPLEVELBANGQI,
    CMD_SPR_CHGJUNQILIFEV, CMD_SPR_NEWJUNQI, CMD_SPR_DELJUNQI, CMD_SPR_LINGDIFORBH, CMD_SPR_CHGHUANGDIROLEID, CMD_SPR_GETBHLINGDIINFODICTBYBHID,
    CMD_SPR_SETLINGDITAX, CMD_SPR_TAKELINGDITAXMONEY, CMD_SPR_GETHUANGDIBHINFO, CMD_SPR_NOTIFYBHZHIWU, CMD_SPR_OPENYANGGONGBK, CMD_SPR_REFRESHYANGGONGBK,
    CMD_SPR_CLICKYANGGONGBK, CMD_SPR_REFRESHQIZHENGE, CMD_SPR_QIZHEGEBUY, CMD_SPR_QUERYQIZHEGEBUYHIST, CMD_SPR_QUICKJINGMAI, CMD_SPR_QUICKHORSEENCHANCE,
    CMD_SPR_QUICKEQUIPENHANCE, CMD_SPR_QUICKEQUIPFORGE, CMD_SPR_GETHUANGDIROLEDATA, CMD_SPR_ADDHUANGFEI, CMD_SPR_REMOVEHUANGFEI, CMD_SPR_GETHUANGFEIDATA,
    CMD_SPR_SENDTOLAOFANG, CMD_SPR_TAKEOUTLAOFANG, CMD_SPR_BANCHAT, CMD_SPR_CHGHUANGHOU, CMD_SPR_GETLINGDIMAPINFO, CMD_SPR_GETHUANGCHENGMAPINFO,
    CMD_SPR_ADDLINGDITAXMONEY, CMD_SPR_INVITEADDHUANGFEI, CMD_SPR_AGREEADDHUANGFEI, CMD_SPR_TASKTRANSPORT, CMD_SPT_LINGLIGUANZHU, CMD_SPR_GETGOODSBYDBID,
    CMD_SPR_QUICKCOMPLETETASK, CMD_SPR_QUERYCHONGZHIMONEY, CMD_SPR_GETFIRSTCHONGZHIDALI, CMD_SPR_NOTIFYBATTLESIDE, CMD_SPR_NOTIFYBATTLEAWARD, CMD_SPR_EXECWABAOBYYAOSHI,
    CMD_SPR_SUBFORGE, CMD_SPR_GETUSERMAILLIST, CMD_SPR_GETUSERMAILDATA, CMD_SPR_FETCHMAILGOODS, CMD_SPR_DELETEUSERMAIL, CMD_SPR_GETMAILSENDCODE,
    CMD_SPR_SENDUSERMAIL, CMD_SPR_RECEIVELASTMAIL, CMD_SPR_EQUIPBORNINDEXUPDATE, CMD_SPR_EQUIPINHERIT, CMD_SPR_QUERYINPUTFANLI,
    CMD_SPR_QUERYINPUTJIASONG, CMD_SPR_QUERYINPUTKING, CMD_SPR_QUERYLEVELKING, CMD_SPR_QUERYEQUIPKING, CMD_SPR_QUERYHORSEKING, CMD_SPR_QUERYJINGMAIKING,
    CMD_SPR_QUERYAWARDHIST, CMD_SPR_EXECUTEINPUTFANLI, CMD_SPR_EXECUTEINPUTJIASONG, CMD_SPR_EXECUTEINPUTKING, CMD_SPR_EXECUTELEVELKING, CMD_SPR_EXECUTEEQUIPKING,
    CMD_SPR_EXECUTEHORSEKING, CMD_SPR_EXECUTEJINGMAIKING, CMD_SPR_MALLZHENQIBUY, CMD_SPR_FETCHACTIVITYAWARD, CMD_SPR_VIPDAILYDATA, CMD_SPR_USEVIPDAILYPRIORITY,
    CMD_SPR_ACTIVITYTRANSPORT, CMD_SPR_YANGGONGBKDAILYDATA, CMD_SPR_FETCHYANGGONGBKJIFENAWARD, CMD_SPR_QUERYSHILIANTAAWARDINFO, CMD_SPR_FETCHSHILIANTAAWARD,
    CMD_SPR_COMPLETETINYCLIENT, CMD_SPR_USERGOLDCHANGE, CMD_SPR_NOTIFYSHENGXIAOGUESSSTAT, CMD_SPR_NOTIFYSHENGXIAOGUESSRESULT, CMD_SPR_ADDSHENGXIAOMORTGAGE,
    CMD_SPR_QUERYROLESHENGXIAOGUESSLIST, CMD_SPR_QUERYSHENGXIAOGUESSHISTORY, CMD_SPR_QUERYSHENGXIAORECENTRESULTLIST, CMD_SPR_QUERYSHENGXIAOGUESSSELFHISTORY,
    CMD_SPR_UPDATETENGXUNFCMRATE, CMD_SPR_NEWNPC, CMD_SPR_DELNPC, CMD_SPR_EXTGRIDBYYUANBAO, CMD_SPR_SUBMONEY, CMD_SPR_EXTBAGNUMBYYUANBAO, CMD_SPR_STOPMOVE,
    CMD_SPR_NOTIFYEQUIPSTRONG,
    CMD_SPR_EXCUTENPCLUATALK, CMD_SPR_EXCUTENPCLUAFUNCTION, CMD_SPR_ARENABATTLE, CMD_SPR_ARENABATTLEKILLEDNUM, CMD_SPR_CITYWARREQUEST, CMD_SPR_TAKELINGDIDAILYAWARD,
    CMD_SPR_NOTIFYOPENWINDOW, CMD_SPR_CHENGJIUDATA, CMD_SPR_FETCHCHENGJIUAWARD, CMD_SPR_DSHIDECMD, CMD_SPR_NEWDECO, CMD_SPR_DELDECO, CMD_SPR_MENDEQUIPMENT,
    CMD_SPR_NOTIFYGOODSINFO, CMD_SPR_ROLEPARAMSCHANGE, CMD_SPR_EQUIPFENJIE, CMD_SPR_JINGYUANEXCHANGE, CMD_SPR_HUIZHANGEXCHANGE, CMD_SPR_ACTIVATNEXTLEVELJINGMAI,
    CMD_SPR_FETCHVIPONCEAWARD, CMD_SPR_TASKTRANSPORT2, CMD_SPR_ACTIVATNEXTLEVELWUXUE, CMD_SPR_CAIJI, CMD_SPR_RUNTASKPLOTLUA,
    CMD_SPR_PLAYGAMEEFFECT, CMD_SPR_TRANSFERSOMETHING, CMD_SPR_CHANGEPETAITYPE, CMD_SPR_FETCHMALLDATA, CMD_SPR_MALLQIANGGOUBUYGOODS,
    CMD_SPR_FETCHZUANHUANGAWARD, CMD_SPR_SETSYSTEMOPENPARAMS, CMD_SPR_ENTERTASKFUBEN, CMD_SPR_GETUPLEVELGIFTOK, CMD_SPR_UPDATEWEIGHTS,
    CMD_SPR_GETTASKAWARDS, CMD_SPR_NOTIFYGETGOODSPACK, CMD_SPR_RESETJINDANBAG, CMD_SPR_GETJINDANGOODSLIST, CMD_SPR_ZAJINDAN, CMD_SPR_QUERYZAJINDANHISTORY,
    CMD_SPR_QUERYSELFZAJINDANHISTORY, CMD_SPR_GETWANGCHENGMAPINFO, CMD_SPR_GETLIMITTIMELOGINGIFT, CMD_SPR_ROLESTATUSCMD, CMD_SPR_GETTO60AWARD, CMD_SPR_GETKAIFUONLINEINFO,
    CMD_SPR_GETDAYCHONGZHIDALI, CMD_SPR_GETJIERIXMLDATA, CMD_SPR_QUERYJIERIDALIBAO, CMD_SPR_QUERYJIERIDENGLU, CMD_SPR_QUERYJIERIVIP, CMD_SPR_QUERYJIERICZSONG, CMD_SPR_QUERYJIERICZLEIJI,
    CMD_SPR_QUERYJIERIZIKA, CMD_SPR_QUERYJIERIXIAOFEIKING, CMD_SPR_QUERYJIERICZKING, CMD_SPR_EXECUTEJIERIDALIBAO, CMD_SPR_EXECUTEJIERIDENGLU, CMD_SPR_EXECUTEJIERIVIP, CMD_SPR_EXECUTEJIERICZSONG, CMD_SPR_EXECUTEJIERICZLEIJI,
    CMD_SPR_EXECUTEJIERIZIKA, CMD_SPR_EXECUTEJIERIXIAOFEIKING, CMD_SPR_EXECUTEJIERICZKING, CMD_SPR_CHGJIERICHENGHAO, CMD_SPR_FACTIVITIESDATA, CMD_SPR_YUANBAOCOMPLETETASK,
    CMD_SPR_QUERYHEFUDALIBAO, CMD_SPR_QUERYHEFUVIP, CMD_SPR_QUERYHEFUCZSONG, CMD_SPR_QUERYHEFUFANLI, CMD_SPR_QUERYHEFUPKKING, CMD_SPR_QUERYHEFUWCKING, CMD_SPR_QUERYXINFANLI,
    CMD_SPR_EXECUHEFUDALIBAO, CMD_SPR_EXECUHEFUVIP, CMD_SPR_EXECUHEFUCZSONG, CMD_SPR_EXECUHEFUFANLI, CMD_SPR_EXECUHEFUPKKING, CMD_SPR_EXECUHEFUWCKING, CMD_SPR_EXECUXINFANLI,
    CMD_SPR_ONEKEYQUICKSALEOUT, CMD_SPR_ACTIVATNEXTLEVELZHANHUN, CMD_SPR_ACTIVATNEXTLEVELRONGYU, CMD_SPR_ACTIVATRONGYUBUFFER, CMD_SPR_LIANLUJINGLIAN, CMD_SPR_ZJDJIFEN,
    CMD_SPR_FETCHZJDJIFENAWARD,
    CMD_SPR_QUERYACTIVITYINFO,  // 客户端请求活动的相关信息 -- 比如冲级豪礼名额 神装领取名额 幸运抽奖次数[7/18/2013 LiaoWei]
    CMD_SPR_XINGYUNCHOUJIANG,   // 幸运抽奖 [7/18/2013 LiaoWei]
    CMD_SPR_QUERYYUEDUCHOUJIANGHISTORY,         // 客户端请求月度抽奖历史(全服玩家)[7/23/2013 LiaoWei]
    CMD_SPR_QUERYSELFQUERYYUEDUCHOUJIANGHISTORY,// 客户端请求月度抽奖历史(玩家自己) [7/23/2013 LiaoWei]
    CMD_SPR_EXECUTEYUEDUCHOUJIANG,              // 客户端点击月度抽奖 [7/23/2013 LiaoWei]
    CMD_SPR_QUERYYUEDUCHOUJIANGINFO,            // 客户端请求月度抽奖信息--能玩的次数和活动期间充值的元宝数 [7/23/2013 LiaoWei]
    CMD_SPR_EXECUTEHUNQIEXCHANGE,               // 客户端发起魂器卖出操作 [8/7/2013 LiaoWei]
    CMD_SPR_EXECUTECHANGEOCCUPATION,            // 客户端发起转职操作  [9/28/2013 LiaoWei]
    CMD_SPR_EXECUTECHANGELIFE,                  // 客户端发起转生操作  [9/28/2013 LiaoWei]
    CMD_SPR_BEGINBLINK,                         // 闪现开始 [10/28/2013 LiaoWei]
    CMD_SPR_ENDBLINK,                           // 闪现结束 [10/28/2013 LiaoWei]
    CMD_SPR_GETROLEUSINGGOODSDATALIST,
    CMD_SPR_EXECUTEPROPADDPOINT,                // 属性加点 [10/31/2013 LiaoWei]
    CMD_SPR_EXECUTERECOMMENDPROPADDPOINT,       // 推荐属性加点 [10/31/2013 LiaoWei]
    CMD_SPR_EXECUTERECLEANPROPADDPOINT,         // 清除属性加点 [10/31/2013 LiaoWei]
    CMD_SPR_QUERYCLEANPROPADDPOINT,             // 请求清除属性加点信息 [2/11/2014 LiaoWei]
    CMD_SPR_BLOODCASTLEBEGINFIGHT,              // 鲲鹏冰巢开始战斗 -- 客户端把桥头的阻挡去掉 [11/7/2013 LiaoWei]
    CMD_SPR_BLOODCASTLEKILLMONSTERAHASDONE,     // 鲲鹏冰巢断桥怪击杀到达限额 -- 客户端把桥尾的阻挡去掉 [11/7/2013 LiaoWei]
    CMD_SPR_BLOODCASTLEENDFIGHT,                // 鲲鹏冰巢结束战斗 -- 客户端显示倒计时界面 [11/7/2013 LiaoWei]
    CMD_SPR_FUBENCLEANOUT,                      // 副本扫荡 [11/15/2013 LiaoWei]
    CMD_SPR_FUBENPASSNOTIFY,                    // 副本通关通告 [11/15/2013 LiaoWei]
    CMD_SPR_QUERYFUBENINFO,                    // 客户端请求副本信息 [11/15/2013 LiaoWei]
    CMD_SPR_ATTACK2,                           // 2号攻击请求 针对于黑龙波等特殊技能 [11/22/2013 LiaoWei]
    CMD_SPR_COMPLETEFLASHSCENE,                // 完成新手场景 [11/30/2013 LiaoWei]
    CMD_SPR_FRESHPLAYERSCENEKILLMONSTERAHASDONE,// 新手场景断桥怪击杀到达限额 -- 客户端把桥尾的阻挡去掉 [12/1/2013 LiaoWei]
    CMD_SPR_REFURBISHTASKSTARLEVEL,             // 客户端刷新任务星级 [12/3/2013 LiaoWei]
    CMD_SPR_COMPLETEDAILYCIRCLETASKFORONCECLICK,// 一键完成日常跑环任务 [12/5/2013 LiaoWei]
    CMD_SPR_ADMIREDPLAYER,                      // 客户端点击崇拜某人的操作 [12/10/2013 LiaoWei]
    CMD_SPR_QUERYBLOODCASTLEINFO,               // 请求鲲鹏冰巢基本信息 [12/14/2013 LiaoWei]
    CMD_SPR_EQUIPAPPENDPROP,                    // 装备追加消息 [12/18/2013 LiaoWei]
    CMD_SPR_BLOODCASTLEPREPAREFIGHT,            // 鲲鹏冰巢准备战斗 -- 客户端显示战斗倒计时 [12/20/2013 LiaoWei]
    CMD_SPR_BLOODCASTLECOMBATPOINT,             // 鲲鹏冰巢战斗积分 -- 客户端显示战斗积分 [12/20/2013 LiaoWei]
    CMD_SPR_BLOODCASTLEKILLMONSTERSTATUS,       // 鲲鹏冰巢杀怪状态 -- 客户端显示杀怪的状态 [12/20/2013 LiaoWei]
    CMD_SPR_QUERYCAMPBATTLEINFO,                // 请求仙谕之战场基本信息 [12/23/2013 LiaoWei]
    CMD_SPR_QUERYDAIMONSQUAREINFO,              // 请求封妖八禁台基本信息 [12/25/2013 LiaoWei]
    CMD_SPR_QUERYDAIMONSQUARETIMERINFO,         // 封妖八禁台时间信息 [12/25/2013 LiaoWei]
    CMD_SPR_QUERYDAIMONSQUAREMONSTERWAVEANDPOINTRINFO,// 封妖八禁台怪物和得分信息 [12/25/2013 LiaoWei]
    CMD_SPR_DAIMONSQUAREENDFIGHT,                // 封妖八禁台结束 [12/25/2013 LiaoWei]
    CMD_SPR_UPDATEEVERYDAYONLINEAWARDGIFTINFO,    // 更新玩家的每日在线信息 [1/12/2014 LiaoWei]
    CMD_SPR_GETEVERYDAYONLINEAWARDGIFT,          // 领取每日在线奖励 [1/12/2014 LiaoWei]
    CMD_SPR_UPDATEEVERYDAYSERIESLOGININFO,      // 更新玩家的连续登陆信息 [1/12/2014 LiaoWei]
    CMD_SPR_GETEVERYDAYSERIESLOGINAWARDGIFT,    // 领取连续登陆奖励 [1/12/2014 LiaoWei]
    CMD_SPR_FRESHPLAYERSCENEOVERTIME,           // 新手场景超时 通知客户端 [1/16/2014 LiaoWei]
    CMD_SPR_UPDATEGETTHINGSFLAG,                // 更新拾取设置
    CMD_SPR_BLOODCASTLEPLAYERNUMNOTIFY,         // 鲲鹏冰巢人数通知 [1/20/2014 LiaoWei]
    CMD_SPR_DAIMONSQUAREPLAYERNUMNOTIFY,        // 封妖八禁台人数通知 [1/20/2014 LiaoWei]
    CMD_SPR_BATTLEPLAYERNUMNOTIFY,              // 仙谕之战人数通知  [1/20/2014 LiaoWei]
    CMD_SPR_EXCHANGEMOJINGANDQIFU,              // 魔晶和祈福兑换 [1/23/2014 LiaoWei]
    CMD_SPR_GETMEDITATEEXP,                     // 获取冥想经验 [1/24/2014 LiaoWei]
    CMD_SPR_GETMEDITATETIMEINFO,                // 获取冥想时间信息 [1/24/2014 LiaoWei]
    CMD_SPR_QUERYTOTALLOGININFO,                // 请求累计登陆数据 [2/11/2014 LiaoWei]
    CMD_SPR_GETTOTALLOGINAWARD,                 // 领取累计登陆奖励 [2/11/2014 LiaoWei]
    CMD_SPR_CHANGELIFEFOREQUIP,                 // 客户端装备转生操作 [2/15/2014 LiaoWei]
    CMD_SPR_FLAKEOFFCHANGELIFEFOREQUIP,         // 客户端装备转生剥离操作 [2/15/2014 LiaoWei]
    CMD_SPR_ONEKEYFINDFRIEND,                   // 点击一键征友 [2/15/2014 LiaoWei]
    CMD_SPR_ONEKEYADDFRIEND,                    // 点击一键加友 [2/15/2014 LiaoWei]
    CMD_SPR_GETVIPAWARD,                        // 获得VIP奖励 [2/20/2014 LiaoWei]
    CMD_SPR_DAILYACTIVEDATA,                    // 获取每日活跃信息 [2/25/2014 LiaoWei]
    CMD_SPR_GETDAILYACTIVEAWARD,                // 获取每日活跃奖励 [2/25/2014 LiaoWei]
    CMD_SPR_SETAUTOASSIGNPROPERTYPOINT,         // 设置自动分配点设置 [3/3/2014 LiaoWei]
    CMD_SPR_GETBLOODCASTLEAWARD,                // 领取鲲鹏冰巢的奖励 [3/8/2014 LiaoWei]
    CMD_SPR_GETDAIMONSQUAREAWARD,               // 领取封妖八禁台的奖励 [3/8/2014 LiaoWei]
    CMD_SPR_GETCOPYMAPAWARD,                    // 领取副本奖励 [3/5/2014 LiaoWei]
    CMD_SPR_GETSKILLINFO,                       // 客户端请求技能信息 [3/17/2014 LiaoWei]
    CMD_SPR_EXPERIENCECOPYMAPINFO,              // 封妖悟真台信息 [3/18/2014 LiaoWei]
    CMD_SPR_ZHANMENGSHIJIAN_DETAIL,             // 联盟事件详情 [3/14/2014 JinJieLong]
    CMD_SPR_KAIFUACTIVITYINFO,                  // 开服活动信息 [3/20/2014 LiaoWei]
    CMD_SPR_GETTHEKINGOFPKINFO,                 // 请求斗仙炼心阵基本信息 [3/22/2014 LiaoWei]
    CMD_SPR_NOTIFYTHEKINGOFPKAWARDINFO,         // 斗仙炼心阵奖励信息 [3/22/2014 LiaoWei]
    CMD_SPR_ANGELTEMPLETIMERINFO,               // 黄泉仙殿时间信息(准备战斗、开始战斗、结束战斗) [12/20/2013 LiaoWei]
    CMD_SPR_ANGELTEMPLEFIGHTEND,                // 黄泉仙殿结束--显示奖励[12/20/2013 LiaoWei]
    CMD_SPR_ANGELTEMPLEFIGHTINFOALL,            // 黄泉仙殿战斗信息--群发 [3/23/2014 LiaoWei]
    CMD_SPR_ANGELTEMPLEFIGHTINFOSINGLE,         // 黄泉仙殿战斗信息--给自己 [3/23/2014 LiaoWei]
    CMD_SPR_ANGELTEMPLESPARK,                   // 黄泉仙殿战力鼓舞 [3/23/2014 LiaoWei]
    CMD_SPR_GETANGELTEMPLEBASEINFO,             // 黄泉仙殿基本信息[3/23/2014 LiaoWei]
    CMD_SPR_QUERYADRATIONPKKINGINFO,            // 请求斗仙炼心阵崇拜信息[3/23/2014 LiaoWei]
    CMD_SPR_ADRATIONPKKING,                     // 斗仙炼心阵崇拜[3/23/2014 LiaoWei]
    CMD_SPR_JINGJI_DETAIL,                      // 试练场详情 [3/24/2014 JinJieLong]   
    CMD_SPR_JINGJI_REQUEST_CHALLENGE,           // 试练场请求挑战 [3/24/2014 JinJieLong]
    CMD_SPR_JINGJI_CHALLENGE_END,               // 试练场挑战结束弹出奖励窗口[3/24/2014 JinJieLong]
    CMD_SPR_JINGJI_NOTIFY_START,                // 试练场通知开始倒计时
    CMD_SPR_JINGJI_CHALLENGEINFO,                // 试练场战报[3/25/2014 JinJieLong]
    CMD_SPR_JINGJI_RANKING_REWARD,              // 试练场领取排行榜奖励[3/25/2014 JinJieLong]
    CMD_SPR_JINGJICHANG_REMOVE_CD,              // 试练场消除挑战CD [3/25/2014 JinJieLong]
    CMD_SPR_JINGJICHANG_GET_BUFF,               // 试练场领取Buff [3/25/2014 JinJieLong]
    CMD_SPR_JINGJICHANG_JUNXIAN_LEVELUP,        // 试练场升级血阶 [3/25/2014 JinJieLong]
    CMD_SPR_JINGJICHANG_LEAVE,                  // 离开试练场消息[3/29/2014 JinJieLong]
    CMD_SPR_CHGFAKEROLELIFEV,                   //假人的血量修改
    CMD_SPR_NEWFAKEROLE,                        //新假人通知
    CMD_SPR_DELFAKEROLE,                        //删除假人
    CMD_SPR_OPENMARKET,                         //打开交易市场
    CMD_SPR_MARKETSALEMONEY,                    //交易市场中上架金币
    CMD_SPR_GETVIPINFO,                         // 玩家请求VIP信息 [3/28/2014 LiaoWei]
    CMD_SPR_GETVIPLEVELAWARD,                   // 玩家领取VIP等级奖励 [3/28/2014 LiaoWei]
    CMD_SPR_VIPLEVELUP,                         // 玩家VIP等级升级 [3/28/2014 LiaoWei]
    CMD_SPR_GETLIXIANBAITANTICKS,               // 获取离线摆摊时长(毫秒)
    CMD_SPR_UPDATELIXIANBAITANTICKS,            // 修改离线摆摊时长(毫秒)
    CMD_SPR_QUERYOPENGRIDTICK,                  // 请求开背包格子时间戳 [4/7/2014 LiaoWei]
    CMD_SPR_QUERYOPENPORTABLEGRIDTICK,          // 请求开随身仓库包裹的时间戳 [4/7/2014 LiaoWei]
    CMD_SPR_STARTMEDITATE,                      // 开始冥想
    CMD_SPR_ZHANMENGBUILDUPLEVEL,               // 联盟建筑升级
    CMD_SPR_ZHANMENGBUILDGETBUFFER,             // 领取联盟建筑的buffer
    CMD_SPR_GETBAITANLOG,                       // 获取摆摊日志
    CMD_SPR_GETPUSHMESSAGEINFO,                 // 客户端把推送信息发给服务器[4/23/2014 LiaoWei]
    CMD_SPR_ACTIVATIONPICTUREJUDGE,             // 激活图鉴 [5/3/2014 LiaoWei]
    CMD_SPR_GETNPICTUREJUDGEINFO,               // 取得图鉴信息 [5/3/2014 LiaoWei]
    CMD_SPR_MUEQUIPUPGRADE,                     // 装备进阶 [4/30/2014 LiaoWei]
    CMD_SPR_WINGUPSTAR,                         // 翅膀升星 [5/4/2014 liuhuicheng]
    CMD_SPR_WINGUPGRADE,                        // 翅膀进阶 [5/4/2014 liuhuicheng]
    CMD_SPR_WINGOFFON,                          // 翅膀佩戴/卸载 [5/4/2014 liuhuicheng]
    CMD_SPR_CHECK,                              // 与服务器心跳，每两秒发一次，校验是否加速
    CMD_SPR_REFERPICTUREJUDGE,                  // 提交图鉴信息 [5/17/2014 LiaoWei]
    CMD_SPR_GETMOJINGEXCHANGEINFO,              // 客户端请求魔晶钻石兑换信息 [5/21/2014 LiaoWei]
    CMD_SPR_REFRESH_ICON_STATE,                 // 刷新图标状态信息 [5/21/2014 ChenXiaojun]
    CMD_SPR_EQUIPAPPENDINHERIT,                 // 追加传承 [5/24/2014 LiaoWei]
    CMD_SPR_SWEEP_WANMOTA,                      // 扫荡封妖谷 [6/5/2014 ChenXiaojun]
    CMD_SPR_UPDATE_SWEEP_STATE,                 // 更新扫荡状态 [6/5/2014 ChenXiaojun]
    CMD_SPR_GET_WANMOTA_DETAIL,                 // 获取封妖谷信息 [6/5/2014 ChenXiaojun]
    CMD_SPR_GET_SWEEP_REWARD,                   // 领取扫荡奖励 [6/5/2014 ChenXiaojun]
    CMD_SPR_LISTCOPYTEAMS,                      // 搜索副本队伍 [6/5/2014 LiTeng]
    CMD_SPR_COPYTEAM,                           // 副本组队命令 [6/5/2014 LiTeng]
    CMD_SPR_COPYTEAMDATA,                       // 副本队伍信息 [6/5/2014 LiTeng]
    CMD_SPR_COPYTEAMSTATE,                      // 副本队伍成员状态变更 [6/5/2014 LiTeng]
    CMD_SPR_REGEVENTNOTIFY,                     // 注册事件通知(副本组队) [6/5/2014 LiTeng]
    CMD_SPR_LISTCOPYTEAMDATA,                   // 队伍列表中的队伍信息变化 [6/5/2014 LiTeng]
    CMD_SPR_COPYTEAMDAMAGEINFO,                 // 队伍成员伤害信息 [6/6/2014 LiTeng]
    CMD_SPR_GOLDCOPYSCENEPREPAREFIGHT,          // 上古灵库准备战斗 -- 客户端显示战斗倒计时 [6/11/2014 LiaoWei]
    CMD_SPR_GOLDCOPYSCENEMONSTERWAVE,           // 上古灵库刷怪波数 [6/11/2014 LiaoWei]
    CMD_SPR_GETNEWZONEACTIVEAWARD,              // 获取新区活动奖 [6/10/2014 gwz]
    CMD_SPR_QUERYUPLEVELMADMAN,                 // 冲级狂人 [6/10/2014 gwz]
    CMD_SPR_QUERYNEWZONEACTIVE,                 // 新区活动 [6/10/2014 gwz]
    CMD_SPR_QUERYUPLEVELGIFTINFO,               // 请求等级奖励领取信息 [6/16/2014 LiTeng]
    CMD_SPR_GETUPLEVELGIFTAWARD,                // 领取等级奖励奖励 [6/16/2014 LiTeng]
    CMD_SPR_JINGJI_START_FIGHT,                 // 试练场战斗开始消息[6/17/2014 ChenXiaojun]
    CMD_SPR_QUERY_REPAYACTIVEINFO,              // 查询回馈活动信息 [6/17/2014 gwz]
    CMD_SPR_GET_REPAYACTIVEAWARD,               // 获取回馈活动奖励 [6/17/2014 gwz]
    CMD_SPR_QUERY_ALLREPAYACTIVEINFO,           // 获取所有回馈信息，充值和消费值 [6/19/2014 gwz]
    CMD_SPR_QUERYACTIVITYSOMEINFO,              // 请求活动(鲲鹏冰巢、封妖八禁台)的一些信息 [7/8/2014 LiaoWei]
                                                //CMD_SPR_DESTROYGOODS,                     //摧毁物品
    CMD_SPR_PLAYBOSSANIMATION,                  //boss出生前通知播放动画
    CMD_SPR_ENDBOSSANIMATION,                   //客户端通知服务器端开始刷新boss（防止外挂，参数有校验）
    CMD_SPR_QUERY_TODAYCANDOINFO,               //查询今日可做 [7/9/2014 gwz]
    CMD_SPR_QUERY_GETOLDRESINFO,                //查询资源找回信息 [7/9/2014 gwz]
    CMD_SPR_GET_OLDRESOURCE,                    //资源找回，领取资源 [7/9/2014 gwz]
    CMD_SPR_EXTENSIONPROPSHITED,                //拓展属性命中通知
    CMD_SPR_EXEC_WASHPROPS,                     //执行装备洗练
    CMD_SPR_EXEC_WASHPROPSINHERIT,              //执行装备洗练传承
    CMD_SPR_BATTLE_SCORE_LIST,                  //仙谕之战积分排名信息 [7/23/2014 lt]
    CMD_SPR_STORYCOPYMAPINFO,                   // 剧情副本信息 [7/24/2014 LiaoWei]
    CMD_SPR_GETUSERMAILCOUNT,                   //获取邮件数量 [7/28/2014 lt]
    CMD_SPR_QUERYIMPETRATEINFO,                 // 请求祈福数据 [7/30/2014 LiaoWei]
    CMD_SPR_EXECUTEIMPETRATE,                   // 执行祈福 [7/30/2014 LiaoWei]
    CMD_SPR_OPENMARKET2,                        //打开交易市场 MU交易所功能修改的第二套交易类指令开始
    CMD_SPR_MARKETSALEMONEY2,                   //交易市场中上架金币
    CMD_SPR_SALEGOODS2,
    CMD_SPR_SELFSALEGOODSLIST2,
    CMD_SPR_OTHERSALEGOODSLIST2,
    CMD_SPR_MARKETROLELIST2,
    CMD_SPR_MARKETGOODSLIST2,
    CMD_SPR_MARKETBUYGOODS2,                    //MU交易所功能修改的第二套交易类指令结束
    CMD_SPR_QUERYSTARCONSTELLATIONINFO,         // 请求星座数据 [8/1/2014 LiaoWei]
    CMD_SPR_EXECUTEACTIVATIONSTARCONSTELLATION, // 激活星座 [8/1/2014 LiaoWei]
    CMD_SPR_CHANGEANGLE, // 修改角色的360角度

    CMD_SPR_UPDATESHARESTATE,                   // 处理分享[8/6/2014 gwz]
    CMD_SPR_GETSHAREAWARD,                      // 发放分享奖励[8/6/2014 gwz]
    CMD_SPR_GETSHARESTATE,                      //获取分享状态
    CMD_SPR_BROADSPECIALHINTTEXT,               // 播放特殊的提示信息，例如boss AI描述
    CMD_SPR_MAPAIEVENT,                         // 发送地图事件，例如清除光幕
    CMD_SPR_EXEC_LIANZHI,                       // 执行炼制
    CMD_SPR_QUERY_LIANZHICOUNT,                 // 查询炼制次数
    CMD_SPR_UPGRADE_CHENGJIU,                   // 提升成就 [9/15/2014 ChenXiaojun]
    CMD_SPR_GETFIRSTCHARGEINFO,                 //获得各个充值档首次充值信息
    CMD_SPR_BATCHFETCHMAILGOODS,                //批量提取邮件
    CMD_SPR_PUSH_VERSION,                       //报告客户端代码版本号
    CMD_SPR_NOTIFYTEAMCHGZHANLI,                 //通知组队队员战力变化
    CMD_SPR_NOTIFYSELFCHGZHANLI,                 //通知自己战力变化
    CMD_SPR_NOTIFYOTHERBUFFERDATA,               //通知他人Buff变化变化
    CMD_SPR_NOTIFYSHOWGONGGAO,                   //登录后获取公告显示信息 [10/28/2014 ChenXiaojun]
    CMD_SPR_GETWINGINFO,                        // 获取翅膀信息
    CMD_SPR_CHENGZHAN_JINGJIA,                  //罗兰城战竞价进攻方资格

    CMD_SPR_GUIDE_STEP = 2005,                  // 客户端上传新手引导步骤[20150604 chenyongcun]
    CMD_SPR_TASK_HORSEOFFON = 2006,             //任务坐骑
    CMD_SPR_GETDROPTHING = 2007,                //告诉服务端执行拾取掉落操作
    CMD_SPR_RENAME = 2008,                      //修改名字（帮会名字）
    CMD_SPR_APPLY_CHARGE_ORDER = 2009,    //申请充值订单消息号
    CMD_SPR_GET_CHARGE_LIST = 2010,    //客户端申请充值列表
    CMD_SPR_KF_GET_ADDRESS = 2011,    // 客户端申请进入跨服的地址

    CMD_SPR_UNDERGROUNDPALACETIMERINFO = 2012,               // 地宫5时间信息(准备战斗、开始战斗、结束战斗) 
    CMD_SPR_UNDERGROUNDPALACEFIGHTEND = 2013,                // 地宫5结束--显示奖励
    CMD_SPR_UNDERGROUNDPALACEFIGHTINFOALL = 2014,            // 地宫5战斗信息--群发
    CMD_SPR_UNDERGROUNDPALACEFIGHTINFOSINGLE = 2015,         // 地宫5斗信息--给自己
    CMD_SPR_UNDERGROUNDPALACESPARK = 2016,                   // 地宫5战力鼓舞
    CMD_SPR_GETUNDERGROUNDPALACEBASEINFO = 2017,             // 地宫5基本信息

    CMD_SPR_CLIENT_EVENT = 2018,             // 客户端提交事件
    CMD_SPR_PUSH_CLIENTVERSION = 2019, //客户端提交字符串的版本号记录到服务端

    //客户端请求进入势力战副本
    CMD_SPR_ORGBATLE_ENTER = 2020,
    //给势力战副本上的玩家广播战斗状态
    CMD_SPR_ORGBATTLE_STATE = 2021,
    //给势力战副本上的玩家广播当前第几阶段
    CMD_SPR_ORGBATTLE_STAGE = 2022,
    //给区域玩家广播是否开启环境伤害特效
    CMD_SPR_ORGBATTLE_EVIROMENTHURT_OPEN = 2023,
    //给区域玩家广播光幕是否开启
    CMD_SPR_ORGBATTLE_DOOR_OPEN = 2024,
    //客户端请求离开势力战副本
    CMD_SPR_ORGBATTLE_LEAVE = 2025,
    //客户端请求势力战开始时间
    CMD_SPR_ORRBATTLE_STARTTIME = 2026,
    //客户端请求国王战参战联盟列表
    CMD_SPR_ORGBATTLE_LIST = 2027,
    //给客户端通知开战倒计时
    CMD_SPR_ORFBATTLE_TICKS = 2028,
    //给客户端通知所有参战势力的存活人数和参战总数
    CMD_SPR_ORGBATTLE_ITEM_LIST = 2029,
    //给客户端通知势力战的获胜势力信息
    CMD_SPR_ORGBATTLE_WIN = 2030,
    //给客户端通知开门条件描述
    CMD_SPR_ORGBATTLE_DOOR_OPEN_DESC = 2031,

    CMD_SPR_KF_BLOCK_RELATION_INFO = 2032, //获取区块关联关系数据
    CMD_SPR_KF_GET_CITY_INFO = 2033, //获取占领信息
    CMD_SPR_KF_SIGNUP = 2034, //玩家报名跨服信息
    CMD_SPR_KF_SIGN_UP_RESULT = 2035,  //跨服报名结果展示数据
                                       //跨服战报名时间（主要用于前端显示跨服战报名倒计时）
    CMD_SPR_KF_REGISTER_TIME = 2036,
    //给客户端米聊数据[2015/10/10 ManGao]
    CMD_SPR_MITALK_DATA = 2037,
    //获取国王帮会信息
    CMD_SPR_GETKINGBANGHUIINFO = 2038,


    CMD_SPR_GET_OUTFITSOUL_EXCHANGE_INFO = 2039,//获取玩家器魂兑换信息消息

    CMD_SPR_GET_DAILY_BUY_LIMIT_INFO = 2040,//获取玩家的每日限购数据
    CMD_SPR_DAILY_BUY_GOODS = 2041,//玩家进行购买每日限购的物品

    CMD_SPR_BH_LIBAO_DATA = 2042,//国王分配的帮会礼包信息
    CMD_SPR_GET_LEAGUE_SKILL = 2043,//获取联盟技能
    CMD_SPR_UPDATE_LEAGUE_SKILL = 2044,//学习联盟技能
    CMD_SPR_CAIJI_START = 2045,//采集开始消息
    CMD_SPR_COMPLETE_XIANMAI_DAILY_TASK = 2046,//客户端提交完成仙脉任务操作

    CMD_SPR_EXCHANGE_TRUMP = 2047,//兑换法宝
    CMD_SPR_TRUMP_STAR_UP = 2048,//法宝升星
    CMD_SPR_TRUMP_LIFTSEAL_CHANGE = 2049,//自动解除封印指令

    CMD_SPR_EXTRA_SETTING = 2050,//打开GM操作面板等指令
    CMD_SPR_TEAM_GET_SAME_MEMBER_DATA = 2051,//取得队伍中同地图的人员数据
    CMD_SPR_TRUMP_ON_OR_OFF = 2052,//玩家穿上或者更换穿戴的法宝
    CMD_SPR_GET_TIME_PERIOD_BUY_LIMIT = 2053,//获取玩家的当前的限时限购数据
    CMD_SPR_TIME_PERIOD_GET_GOODS_OK = 2054,//通知客户端期间限购给物品了
    CMD_SPR_GET_COLECT_NUMBER = 2055,//获取采集怪物的数据

    CMD_SPR_GET_FAMILYFULI = 2056,//国王帮会福利礼包
    CMD_SPR_GET_FAMILYFULI_INFO = 2057,// 查询是否可以领取礼包  string 0 可以领取 1 不可领取

    CMD_SPR_GET_YDCJ_RANKING = 2058,//查询月度抽奖排行数据
    CMD_SPR_GET_YDCJ_RANKING_CONFIG = 2059,//获取抽奖数据的xml配置内容

    CMD_SPR_GET_VIP_LEV_DAILY_INFO = 2060, //获取VIP等级每日奖励信息
    CMD_SPR_UPDATE_VIP_LEV_DAILY_INFO = 2061, //更新VIP等级每日奖励信息
    CMD_SPR_GET_VIP_DAILY_BUY_INFO = 2062, //获取玩家的VIP每日购买数据
    CMD_SPR_UPDATE_VIP_DAILY_BUY = 2063, //更新VIP每日购买情况

    CMD_SPR_NEW_ACTIVITY_INIT = 2064, //新活动入口初始化
    CMD_SPR_NEW_ACTIVITY_EVENT = 2065, //新活动事件入口

    CMD_SPR_QUERY_XINFU_BUY_VIP_ITEM = 2085,  //7日活动新服 一折抢购 查询
    CMD_SPR_GET_XINFU_BUY_VIP_ITEM = 2086,  //7日活动新服 一折抢购 领取


    CMD_SPR_BUY_OPEN_SERVICE_FUND = 2100,//购买开服基金消息
    CMD_SPR_OPEN_SERVICE_FUND_STATUS = 2101,//获取开服基金状态数据
    CMD_SPR_GET_OPEN_SERVICE_FUND_AWRAD = 2102,//领取开服基金
    CMD_SPR_LEAGUE_HELP_TRANSPORT = 2103,//联盟帮主传送

    CMD_SPR_NEW_ACTIVITY_QUERY_PBDATA = 2066,//活动初始化数据

    CMD_SPR_FLOW_ENEMY = 2067, //追随仇人的脚步

    CMD_SPR_MONSTER_DROP_EXTRA_MONEY = 2068, //怪物额外掉落金币
    CMD_SPR_KING_BANGHUI_EFFECT_GONEAWAY = 2069, //国王帮会效果消失
    CMD_SPR_GET_ACCOUNT_CREATE_TIME = 2070,//获取账号创建时间
    CMD_SPR_KING_AND_KINGBANGHUI_NAME = 2071,//给客户端推送国网名字和帮会名字
                                             //帮会竞拍国王战名额
    CMD_SPR_BANGHUI_AICTION = 2072,
    //帮会竞拍国王战名额列表
    CMD_SPR_BANGHUI_AICTION_LIST = 2073,
    //获取当前时间下帮会功能类型
    CMD_SPR_BANGHUI_HUODONG_STATE = 2074,
    //获取帮会竞拍功能相关的时间
    CMD_SPR_BANGHUI_AUCTION_TIME = 2075,
    //帮会竞拍国王战名额结算
    CMD_SPR_BANGHUI_AUCTION_BALANCE = 2076,
    //国王战开始弹窗提醒
    CMD_SPR_BANGHUI_ENTER_NOTICE = 2077,
    //跨服战胜利奖励
    CMD_SPR_KUAFUAWARD_DATA = 2078,
    CMD_SPR_GET_MY_YDCJ_CNT = 2079,//玩家查询自己的抽奖次数
    CMD_SPR_EXECUTE_CHOUJIANG = 2080,//玩家执行抽奖操作

    CMD_SPR_UPDATE_ELEMENT_ZHENGLI = 2091,//整理元素之心
    CMD_SPR_UP_ELEMENT = 2092,//吞噬元素之心
    CMD_SPR_PEIDAI_XIEXIA = 2093,//佩戴、卸下元素
    CMD_SPR_GET_ELEMENT = 2094,//提炼（获取）元素
    CMD_SPR_GET_ELEMENT_DIMOND = 2095,//提炼（获取）钻石元素
    CMD_SPR_SERVER_ELEMENT_UPDATE = 2096,//服务器元素系统更新
    CMD_SPR_USE_HUODONG_BOX = 2097,//开启道具宝箱

    CMD_SPR_FANHUAN = 2099, //内测充值返还
    CMD_SPR_JINGLING_PEIDAI_XIEXIA = 2110,//出库,入库精灵
    CMD_SPR_JINGLING_UPDATE = 2111,//精灵数据更新
    CMD_SPR_JINGLING_LEVEL_UP = 2112,//精灵升级
    CMD_SPR_JINGLING_FIGHT = 2113,//精灵出战,休战
    CMD_SPR_JINGLING_CALL = 2114,//抽取精灵
    CMD_SPR_JINGLING_BROAD_CAST = 2115,//广播场景精灵状态

    CMD_SPR_SERVER_SHOWERROR = 2200,//服务器提示信息 lihongyu
    CMD_SPR_SEND_DEVICE_ROLE = 2201,//收集客户端信息 lihongyu

    CMD_SPR_GET_XIANMAI_CHONGZHU_DATAS = 2300, //客户端查询玩家所有仙脉重铸数据
    CMD_SPR_EXECUTE_XIANMAI_CHONGZHU = 2301,//客户端请求仙脉重铸
    CMD_SPR_SAVE_XIANMAI_CHONGZHU = 2302,//客户端请求保存仙脉数据

    CMD_SPR_SCHOOL_TEACHER_STDUENT_INFO = 4000,//师徒初始化数据
    CMD_SPR_SCHOOL_FIND_TEACHER = 4001,//查找师傅
    CMD_SPR_SCHOOL_FIND_STUDENT = 4002,//查找徒弟
    CMD_SPR_SCHOOL_APPLY_ADD_TEACHER = 4003,//拜师
    CMD_SPR_SCHOOL_APPLY_ADD_STUDENT = 4004,//收徒
    CMD_SPR_SCHOOL_NOTIFY_LIST_STUDENT = 4005,//更新徒弟申请列表
    CMD_SPR_SCHOOL_NOTIFY_LIST_TEACHER = 4006,//更新师傅申请列表
    CMD_SPR_SCHOOL_AGREE_ADD_STUDENT = 4007, // 同意收徒
    CMD_SPR_SCHOOL_AGREE_ADD_TEACHER = 4008,//同意拜师
    CMD_SPR_SCHOOL_LEAVEL_TEACHER = 4009,//叛逃师门
    CMD_SPR_SCHOOL_REMIND_SEND_BOX = 4010,//提醒师傅传功
    CMD_SPR_SCHOOL_NOTIFY_SEND_BOX_DATA = 4011, //师傅收到徒弟传功
    CMD_SPR_SCHOOL_SEND_BOX = 4012,//传功，送宝箱
    CMD_SPR_SCHOOL_UN_LOCK_BOX = 4013,//解锁宝箱
    CMD_SPR_SCHOOL_OPEN_BOX = 4014, //开宝箱
    CMD_SPR_SCHOOL_NOTIFY_BOX_DATA = 4015, //更新宝箱数据
    CMD_SPR_SCHOOL_SETTING_CLOSED = 4016,//设置师徒屏蔽
    CMD_SPR_SCHOOL_NOTIFY_SEND_BOX = 4017,//通知徒弟师傅传功

    CMD_SPR_LEAGUE_UPDATE_ACTIVITY_STATUS = 4200,//联盟活动更新
    CMD_SPR_LEAGUE_ACTIVITY_OPEN = 4201,//联盟活动开启
    CMD_SPR_LEAGUE_CURRENT_ACTIVITY_STATUS = 4202,//当前联盟活动信息
    CMD_SPR_LEAGUE_BOSS_DAMAGE = 4203,//联盟boss伤害排行
    CMD_SPR_LEAGUE_BOSS_AWARD = 4204,//联盟boss奖励
    CMD_SPR_LEAGUE_GM_REMOVE_ACTIVITY = 4205,//删除联盟活动的记录

    CMD_SPR_FAMILYQUESTION_CONFIG = 4210,
    CMD_SPR_ASK_FAMILYQUESTIONS = 4211,
    CMD_SPR_SUBMIT_FAMILYQUESTIONANSWER = 4212,
    CMD_SPR_RECEIVE_FAMILYQUESTIONANSWER = 4213,
    CMD_SPR_RECIEVE_FAMILYQUESTIONANSWERLIST = 4214,


    //推广消息
    CMD_SPR_TUIGUANG = 5090,
    //推广成就协议
    CMD_SPR_TUIGUANG_CHENGJIU = 5091,
    CMD_SPR_TUIGUANG_REG_INVITED = 5092,//成为别人下线

    CMD_SPR_NOTIFY_GEM_ORE_DATA = 5093,//通知矿车血量
    CMD_SPR_NOTIFY_GEM_ADD_DIHUO = 5094,//通知出现地火
    CMD_SPR_NOTIFY_GEM_ADD_TIANLEI = 5095,//通知出现天雷
    CMD_SPR_NOTIFY_GEM_REWARD_DATA = 5096,//奖励界面

    CMD_SPR_SHOUHUNOTIFY = 6000,//守护师姐通知消息
    CMD_SPR_SHOUHU_ADDMONSTER = 6001,//守护师姐，增加npc数据
    CMD_SPR_SHOUHU_REMOVEMONSTER = 6002,//守护师姐，删除npc数据
    CMD_SPR_SHOUHU_UPDATEMONSTER = 6003,//守护师姐，更新npc数据
    CMD_SPR_SHOUHU_GET_NPC = 6004,//守护师姐，请求npc数据

    CMD_SPR_YUEKA_GET_INFO = 6005,//月卡，请求月卡信息
    CMD_SPR_YUEKA_GET_ITEM = 6006,//月卡，获得月卡奖励

    //----------宝石系统消息号------------//
    CMD_SPR_GEMSTONE_INITIALIZE = 6500,                         //初始化宝石数据
    CMD_SPR_GEMSTONE_SYNTHESIZED = 6501,                        //合成宝石
    CMD_SPR_GEMSTONE_PUNCH = 6502,                              //宝石打孔
    CMD_SPR_GEMSTONE_WASHLINE = 6503,                           //宝石洗连
    CMD_SPR_GEMSTONE_STONE_ONE_REPLACE = 6504,                  //宝石镶嵌 更换
    CMD_SPR_GEMSTONE_ONE_KEY_REPLACE = 6505,                    //一键更换宝石

    //积分商城
    CMD_SPR_RECHARGEPOINTMALL = 7000,//积分商城

    CMD_SPR_QUERYJIERIBOSS = 7001,//节日boss
    CMD_SPR_QUERY_JIERI_TOTALLOGININFO = 7002,//客户端请求查询节日累计登录
    CMD_SPR_GETJIERITOTALLOGIN = 7003,//客户端请求领取节日累计登录
    CMD_SPR_ENTER_BANGHUILINGDI = 7004,//客户端请求进入帮会领地
    CMD_SPR_QUERY_JIERI_CONSUMEINFO = 7005,//客户端请求查询节日消费
    CMD_SPR_GETJIERITOTALCONSUME = 7006,//客户端请求领取节日累计消费奖励

    CMD_SPR_OPEN_PANIC_BUYING = 7100,//获取限时抢购数据
    CMD_SPR_OPEN_PANIC_BUYINGREFRESH = 7101,//限时抢购购买

    CMD_COMMENTLEAD = 9000, //评论引导奖励
    CMD_COMMENTLEADQUERYSTATUS = 9001,  //评论引导奖励

    CMD_DB_START_CMD = 10000,//数据库命令
    CMD_DB_UPDATE_POS, CMD_DB_UPDATE_EXPLEVEL, CMD_DB_UPDATE_INTERPOWER,
    CMD_DB_UPDATEMONEY1_CMD, CMD_DB_ADDGOODS_CMD, CMD_DB_UPDATEGOODS_CMD,
    CMD_DB_UPDATETASK_CMD, CMD_DB_UPDATEPKMODE_CMD, CMD_DB_UPDATEPKVAL_CMD, CMD_DB_UPDATEKEYS,
    CMD_DB_UPDATEUSERMONEY_CMD, CMD_DB_UPDATEUSERYINLIANG_CMD, CMD_DB_MOVEGOODS_CMD, CMD_DB_UPDATE_LEFTFIGHTSECS,
    CMD_DB_ROLE_ONLINE, CMD_DB_ROLE_HEART, CMD_DB_ROLE_OFFLINE, CMD_DB_GET_CHATMSGLIST,
    CMD_DB_HORSEON, CMD_DB_HORSEOFF, CMD_DB_PETOUT, CMD_DB_PETIN, CMD_DB_ADDDJPOINT, CMD_DB_UPJINGMAI_LEVEL,
    CMD_DB_REGUSERID, CMD_DB_BANROLENAME, CMD_DB_BANROLECHAT, CMD_DB_GETBANROLECATDICT, CMD_DB_ADDBULLMSG, CMD_DB_REMOVEBULLMSG,
    CMD_DB_GETBULLMSGDICT, CMD_DB_UPDATEONLINETIME, CMD_DB_GAMECONFIGDICT, CMD_DB_GAMECONIFGITEM, CMD_DB_RESETBIGUAN,
    CMD_DB_ADDSKILL, CMD_DB_UPSKILLINFO, CMD_DB_UPDATEJINGMAIEXP, CMD_DB_UPDATEDEFSKILLID, CMD_DB_UPDATEAUTODRINK,
    CMD_DB_UPDATEDAILYTASKDATA, CMD_DB_UPDATEDAILYJINGMAI, CMD_DB_UPDATENUMSKILLID, CMD_DB_UPDATEPBINFO, CMD_DB_UPDATHUODONGINFO,
    CMD_DB_SUBCHONGZHIJIFEN, CMD_DB_USELIPINMA, CMD_DB_UPDATEFUBENDATA, CMD_DB_GETFUBENSEQID, CMD_DB_UPDATEROLEDAILYDATA,
    CMD_DB_UPDATEBUFFERITEM, CMD_DB_UNDELROLENAME, CMD_DB_ADDFUBENHISTDATA, CMD_DB_UPDATELIANZHAN, CMD_DB_UPDATEKILLBOSS, CMD_DB_UPDATEROLESTAT,
    CMD_DB_UPDATEYABIAODATA, CMD_DB_UPDATEYABIAODATASTATE, CMD_DB_UPDATEBATTLENAME, CMD_DB_ADDMALLBUYITEM, CMD_DB_GETLIPINMAINFO,
    CMD_DB_UPDATECZTASKID, CMD_DB_GETTOTALONLINENUM, CMD_DB_UPDATEBATTLENUM, CMD_DB_UPDATEHEROINDEX, CMD_DB_FORCERELOADPAIHANG, CMD_DB_ADDYINPIAOBUYITEM,
    CMD_DB_DELROLENAME,
    CMD_DB_QUERYUMBYNAME, // 从数据库中获取玩家充值日志中的充值真实钱的数目
    CMD_DB_QUERYBHMGRLIST, CMD_DB_UPDATEBANGGONG_CMD, CMD_DB_UPDATEBHTONGQIAN_CMD, CMD_DB_GETBHJUNQILIST,
    CMD_DB_GETBHLINGDIDICT, CMD_DB_UPDATELINGDIFORBH, CMD_DB_GETLEADERROLEIDBYBHID, CMD_DB_ADDBHTONGQIAN_CMD, CMD_DB_ADDQIZHENGEBUYITEM,
    CMD_DB_UPDATEJIEBIAOINFO, CMD_DB_ADDREFRESHQIZHENREC, CMD_DB_CLEARCACHINGROLEIDATA, CMD_DB_ADDMONEYWARNING, CMD_DB_QUERYCHONGZHIMONEY,
    CMD_DB_ADDYINLIANGBUYITEM, CMD_DB_ADDBANGGONGBUYITEM, CMD_DB_SENDUSERMAIL, CMD_DB_GETUSERMAILDATA, CMD_DB_FINDROLEID_BYROLENAME, CMD_DB_QUERYLIMITGOODSUSEDNUM,
    CMD_DB_UPDATELIMITGOODSUSEDNUM, CMD_DB_UPDATEDAILYVIPDATA, CMD_DB_UPDATEDAILYYANGGONGBKJIFENDATA, CMD_DB_UPDATESINGLETIMEAWARDFLAG, CMD_DB_ADDSHENGXIAOGUESSHIST,
    CMD_DB_UPDATEUSERGOLD_CMD, CMD_DB_ADDGOLDBUYITEM, CMD_DB_UPDATEROLEBAGNUM, CMD_DB_SETLINGDIWARREQUEST, CMD_DB_UPDATEGOODSLIMIT, CMD_DB_UPDATEROLEPARAM,
    CMD_DB_ADDQIANGGOUBUYITEM, CMD_DB_ADDQIANGGOUITEM, CMD_DB_QUERYCURRENTQIANGGOUITEM, CMD_DB_QUERYQIANGGOUBUYITEMS, CMD_DB_UPDATEQIANGGOUTIMEOVER,
    CMD_DB_GETBANGHUIMINIDATA, CMD_DB_ADDBUYITEMFROMNPC, CMD_DB_ADDZAJINDANHISTORY, CMD_DB_QUERYQIANGGOUBUYITEMINFO, CMD_DB_QUERYFIRSTCHONGZHIBYUSERID,
    CMD_DB_QUERYKAIFUONLINEAWARDROLEID, CMD_DB_ADDKAIFUONLINEAWARD, CMD_DB_ADDGIVEUSERMONEYITEM, CMD_DB_QUERYKAIFUONLINEAWARDLIST,
    CMD_DB_ADDEXCHANGE1ITEM, CMD_DB_ADDEXCHANGE2ITEM, CMD_DB_ADDEXCHANGE3ITEM, CMD_DB_ADDFALLGOODSITEM, CMD_DB_UPDATEROLEPROPS, CMD_DB_QUERYTODAYCHONGZHIMONEY,
    CMD_DB_QUERYDAYCHONGZHIBYUSERID, CMD_DB_CLEARALLCACHINGROLEDATA,
    CMD_DB_QUERYXINGYUNORYUEDUCHOUJIANGINFO,    // GS-DB 询问幸运或月度抽奖信息 [7/17/2013 LiaoWei]
    CMD_DB_EXECUXINGYUNORYUEDUCHOUJIANGINFO,    // GS-DB 更新幸运或月度抽奖信息 [7/17/2013 LiaoWei]
    CMD_DB_ADDYUEDUCHOUJIANGHISTORY,            // GS-DB 增加月度抽奖历史信息 [7/23/2013 LiaoWei]
    CMD_DB_EXECUTECHANGEOCCUPATION,             // GS-DB 转职操作  [9/28/2013 LiaoWei]
    CMD_DB_QUERYBLOODCASTLEENTERCOUNT,          // GS-DB 请求鲲鹏冰巢进入次数[11/6/2013 LiaoWei]
    CMD_DB_UPDATEBLOODCASTLEENTERCOUNT,         // GS-DB 更新鲲鹏冰巢进入次数[11/6/2013 LiaoWei]
    CMD_DB_QUERYFUBENHISINFO,                   // GS-DB 请求副本历史信息 [11/16/2013 LiaoWei] 
    CMD_DB_CLEANDATAWHENFRESHPLAYERLOGOUT,      // GS-DB 在新手阶段掉线处理 [12/2/2013 LiaoWei]
    CMD_DB_FINISHFRESHPLAYERSTATUS,             // GS-DB 结束新手阶段 [12/2/2013 LiaoWei]
    CMD_DB_EXECUTECHANGETASKSTARLEVEL,          // GS-DB 改变任务星级等级[12/3/2013 LiaoWei]
    CMD_DB_EXECUTEUPDATEROLESOMEINFO,           // GS-DB 更新角色的一些信息 [12/17/2013 LiaoWei]
    CMD_DB_QUERYDAYACTIVITYTOTALPOINT,          // GS-DB 请求日常活动最高积分信息 [12/24/2013 LiaoWei]
    CMD_DB_QUERYDAYACTIVITYSELFPOINT,           // GS-DB 请求自己的日常活动积分信息 [12/24/2013 LiaoWei]
    CMD_DB_UPDATEDAYACTIVITYSELFPOINT,          // GS-DB 更新自己的日常活动积分信息 [12/24/2013 LiaoWei]
    CMD_DB_QUERYEVERYDAYONLINEAWARDGIFTINFO,    // GS-DB 请求每日在线奖励信息 [1/12/2014 LiaoWei]
    CMD_DB_ADD_ZHANMENGSHIJIAN,                 // GS-DB 请求请求添加联盟事件 [3/14/2014 JinJieLong]
    CMD_DB_ZHANMENGSHIJIAN_DETAIL,              // GS-DB 请求联盟事件详情 [3/14/2014 JinJieLong]
    CMD_DB_JINGJICHANG_GET_DATA,                // GS-DB 请求获取玩家试练场数据 [3/21/2014 JinJieLong]
    CMD_DB_JINGJICHANG_GET_CHALLENGE_DATA,      // GS-DB 请求获取试练场被挑战者mini数据 [3/21/2014 JinJieLong]
    CMD_DB_JINGJICHANG_CREATE_DATA,             // GS-DB 请求创建试练场数据 [3/22/2014 JinJieLong]
    CMD_DB_JINGJICHANG_REQUEST_CHALLENGE,       // GS-DB 试练场请求挑战 [3/22/2014 JinJieLong]
    CMD_DB_JINGJICHANG_CHALLENGE_END,           // GS-DB 试练场挑战结束 [3/22/2014 JinJieLong]
    CMD_DB_JINGJICHANG_SAVE_DATA,               // GS-DB 保存试练场数据 [3/22/2014 JinJieLong]
    CMD_DB_JINGJICHANG_ZHANBAO_DATA,            // GS-DB 获取试练场战报数据 [3/22/2014 JinJieLong]
    CMD_DB_JINGJICHANG_REMOVE_CD,               // GS-DB 消除挑战CD [3/25/2014 JinJieLong]
    CMD_DB_JINGJICHANG_GET_RANKING_AND_NEXTREWARDTIME,// GS-DB 获取排名和下次领取奖励时间 [3/25/2014 JinJieLong]
    CMD_DB_JINGJICHANG_UPDATE_NEXTREWARDTIME,   // GS-DB  更新下次领取试练场排行榜奖励时间 [3/25/2014 JinJieLong]
    CMD_DB_ADD_BAITANLOG,                       // GS-DB 请求请求添加摆摊日志
    CMD_DB_UPDATEPUSHMESSAGEINFO,               // GS-DB 更新推送信息 [4/23/2014 LiaoWei]
    CMD_DB_QUERYPUSHMESSAGEUSERLIST,            // GS-DB 请求要推送的玩家列表 [4/23/2014 LiaoWei]
    CMD_DB_ADDWING,                             // GS-DB 请求得到第一个翅膀[4/30/2014, liuhuicheng]
    CMD_DB_MODWING,                             // GS-DB 请求修改翅膀[4/30/2014, liuhuicheng]
    CMD_DB_REFERPICTUREJUDGE,                   // GS-DB 提交图鉴信息 [5/18/2014 LiaoWei]
    CMD_DB_QUERYMOJINGEXCHANGEINFO,             // GS-DB 请求绑定钻石兑换信息 [5/21/2014 LiaoWei]
    CMD_DB_UPDATEMOJINGEXCHANGEINFO,            // GS-DB 更新绑定钻石兑换信息 [5/21/2014 LiaoWei]
    CMD_DB_MODIFY_WANMOTA,                      // GS-DB 修改封妖谷表数据 [6/6/2014 ChenXiaojun]
    CMD_DB_GET_WANMOTA_DETAIL,                  // GS-DB 获取封妖谷信息 [6/6/2014 ChenXiaojun]
    CMD_DB_QUERY_REPAYACTIVEINFO,               // GS-DB 查询回馈活动信息
    CMD_DB_GET_REPAYACTIVEAWARD,                // GS-DB 获取回馈活动奖励
    CMD_DB_UPDATE_ACCOUNT_ACTIVE,               // GS-DB 更新帐户活跃信息  [7/9/2014 ChenXiaojun]
    CMD_DB_QUERY_GETOLDRESINFO,                 // GS-DB 查询资源找回信息 [7/11/2014 gwz]
    CMD_DB_UPDATE_OLDRESOURCE,                  // GS-DB 资源找回，领取资源 [7/11/2014 gwz]
    CMD_DB_UPDATEGOODS_CMD2,                    // GS-DB 更新物品扩展信息(装备洗练等)
    CMD_DB_UPDATESTARCONSTELLATION,             // GS-DB 激活星座更新星座信息 [8/1/2014 LiaoWei]
    CMD_DB_SAVECONSUMELOG,                      // GS-DB 保存钻石消费信息 [8/19/2014 gwz]
    CMD_DB_QUERYVIPLEVELAWARDFLAG,              // GS-DB 玩家领取VIP等级奖励 [8/21/2014 LiaoWei]
    CMD_DB_UPDATEVIPLEVELAWARDFLAG,             // GS-DB 玩家更新VIP等级奖励标记信息 [8/21/2014 LiaoWei]
    CMD_DB_UPDATEFIRSTCHARGE,                   // GS-DB 玩家更新首充信息 [9/16/2014 gwz]
    CMD_DB_FIRSTCHARGE_CONFIG,                  // GS-DB 启动时发送给db首充配置表 [12/11/2014 gwz]

    CMD_DB_UPDATE_ROEL_DATA_ADDONS_IPVIPTUTORIASTEP,   //GS-DB 请求更新角色附加信息：最后登陆IP，vip，引导[20150604]
    CMD_DB_UPDATE_ROLE_DATA_ADDONS_FIRSTIP,   //GS-DB 创建角色请求更新角色附加信息[20150604]

    CMD_DB_GET_KUAFU_BLOCK_RELATION_INFO,   //GS-DB 获取跨服的城池区块关联关系
    CMD_DB_KUAFU_JOININ,   //GS-DB 跨服进入时调用DBS发送玩家的数据到跨服区
    CMD_DB_KUAFU_SIGN_UP_TO_DBS,   //GS-DB 玩家报名时将跨服上面的数据发送到跨服DBS保存，本消息为与本机DBS交互的消息
    CMD_DB_KUAFU_GET_REGISTER_DATA, //GS-DB 获取玩家报名信息，该指令主要作用是普通服的GS向DBS发起获取报名结果的指令
    CMD_DB_GET_KUAFU_RESULT,  //GS-DB 获取跨服结果的所有信息的数据
    CMD_DB_GET_KUAFU_SIGNUP_BY_BHID, //GS-DB获取跨服所在的区的报名信息

    CMD_DB_GET_SERVERLIST = 11000,
    CMD_DB_ONLINE_SERVERHEART = 11001,
    CMD_DB_RELOAD_KUAFURESULT = 11002,//重载跨服结果从DB中更新
    CMD_DB_UPDATE_CAIJI_DATA = 11100,//更新玩家的采集数据
    CMD_DB_QUERYOSEXCHANGEINFO = 11101,             // 请求器魂兑换信息
    CMD_DB_UPDATEOSEXCHANGEINFO = 11102,            //更新器魂兑换信息
    CMD_DB_DAILY_BUY_LIMIT_ADD_UPDATE = 11103, //添加或者更新玩家的每日限购数据
    CMD_DB_QUERY_KING_GIFT = 11104,// 查询玩家的国王分发礼包数据
    CMD_DB_QUERY_BH_MEMBER_LIST = 11105,// 查询玩家帮会列表数据
    CMD_DB_SAVE_KING_GIFT = 11106, //保存玩家的国王礼包数据
    CMD_DB_CLEAN_KING_GIFT = 11107, //清空所有玩家的国王礼包数据
    CMD_DB_UPDATE_VIP_LEVEL = 11108,    //保存玩家的VIP等级数据到数据库备GM工具查询用
    CMD_DB_UPDATE_USER_BETA_TEST_REWARD = 11109, //更新用户的查询状态
    CMD_DB_UPDATE_LEAGUE_SKILL = 11110,//更新玩家的联盟技能数据

    CMD_DB_ADD_TRUMP = 11111,//添加玩家的法宝数据到DB
    CMD_DB_UPDATE_TRUMP = 11112,//更新玩家的法宝数据到DB
    CMD_DB_UPDATE_TIME_PERIOD_BUY_LIMIT = 11113,//存储/更新玩家的期间购买数据
    CMD_DB_GET_TIME_PERIOD_BUY_LIMIT = 11114,//单独获取玩家的期间购买数据
    CMD_DB_SEND_USERID_CHAECK_CONFIG = 11115,//发送服务器配置信息

    CMD_GET_GOODS_LIST_BY_SITE = 11200,//根据位置获取玩家的物品列表
    CMD_NAME_REGISTERNAME = 12000,             //注册名字到名字服务器

    CMD_DB_GET_YDCJ_RANKING = 12001,//获取月度抽奖的历史排行
    CMD_DB_GET_YDCJ_BY_RID_CNT = 12002,//按照角色ID获取活动期间内的抽奖次数
    CMD_DB_ADD_YDCJ_RANKING_HISTORY = 12003,//保存玩家的抽奖排名的记录

    CMD_DB_GET_ROLE_PARAM_NEW = 12005,//获得玩家角色参数  

    CMD_DB_GETROLEGMCOMMANDLIST = 13000,         // 从数据库服中查询出GM指令
    CMD_DB_GETROLESYSMAILLIST = 13001,         // 从数据库服中查询出未领取过的系统邮件奖励

    //GS-DB 请求mitalk Data [2015/10/23 ManGao]
    CMD_DB_GET_MITALK_DATA = 13002,
    CMD_DB_SAVE_MITALK_DATA = 13003,

    CMD_DB_GET_ROLE_ZONEID = 13004,//从DB获取角色的ZoneID


    //检查玩家是否有新服活动可领取
    CMD_DB_ISCAN_GETACTIVITY_AWARD = 13992,
    //检查玩家是否可以领取每日任务奖励
    CMD_DB_ISCAN_GETDAILYTASK_AWARD = 13993,
    //初始化角色每日任务活动
    CMD_INIT_ROLE_ACTIVITY_DAILYTASK = 13994,
    //检查并更新角色的每日任务
    CMD_DB_ROLE_ACTIVITY_CHECKANDUPDATE_DAILYTASK = 13995,
    //查询角色的每日任务
    CMD_QUERY_ROLE_ACTIVITY_DAILYTASK = 13996,
    //更新角色每日任务
    CMD_DB_UPDATE_ROLE_ACTIVITY_DAILYTASK = 13997,
    //初始化角色每日任务数据
    CMD_DB_INIT_ROLE_ACTIVITY_DAILYTASK = 13998,
    //依据Servicetype查询全局配置参数
    CMD_DB_QUERY_GAME_GLOBAL_LOGIC_BY_SERVICETYPE = 13999,


    //更新业务逻辑参数。如国王ID，参与国王战的玩家列表，参与跨服战的玩家列表等等
    CMD_DB_UPDATA_GAME_GLOBAL_LOGIC_PARAM = 14000,
    //查询游戏业务逻辑参数。如国王ID，参与国王战的玩家列表，参与跨服战的玩家列表等等
    CMD_DB_QUERY_GAME_GLOBAL_LOGIC_PARAM = 14001,
    //GS-DB GS向DB发起分战场请求 [2015/09/22 张林]
    CMD_DB_GENERATOR_BATTLE = 14002,
    //获取在同一战场中的跨服战斗对象 [2015/10/22 张林]
    CMD_DB_GETKUAFUDATA_IN_BATTLE = 14003,
    //更改城池主人[2015/10/26]
    CMD_DB_UPDATE_CITY_OWNER = 14004,
    //同步服务器相关的数据到跨服去
    CMD_DB_SYNC_SERVERINFO_TO_KUAFU = 14005,
    //GS-DB通过ServerID获取跨服战结果数据
    CMD_DB_GET_KUAFU_SIGNUP_BY_SERVERID = 14006,
    //GS-DB更新跨服战战斗结果
    CMD_DB_UPDATE_KUAFU_BATTLE_RESULT = 14007,
    //GS-DB清除跨服战战斗结果
    CMD_DB_CLEAN_KUAFU_BATTLE_RESULT = 14008,
    //GS-DB获取跨服战初始城池
    CMD_DB_GET_KUAFU_INITAL_CITY = 14009,

    CMD_DB_QUERY_VIP_LEV_DAILY_AWARD_FLAG = 14010,              // GS-DB 玩家领取VIP等级每日奖励
    CMD_DB_UPDATE_VIP_LEV_DAILY_AWARD_FLAG = 14011,             // GS-DB 玩家更新VIP等级每日奖励
    CMD_DB_QUERY_VIP_DAILY_BUY_FLAG = 14012,              // GS-DB 玩家领取VIP每日购买数据
    CMD_DB_UPDATE_VIP_DAILY_BUY_FLAG = 14013,             // GS-DB 玩家更新VIP每日购买情况

    CMD_DB_DAY7_CHARGE_DATA_INIT = 14014,             //GS-DB 7天活动每日充值
    CMD_DB_DAY7_CHARGE_DATA_UPDATE = 14015,             //GS-DB 更新7天活动每日充值

    CMD_DB_DAY7_LOGIN_DATA_INIT = 14016,             //GS-DB 7天活动每日登录
    CMD_DB_DAY7_LOGIN_DATA_UPDATE = 14017,             //GS-DB 更新7天活动每日登录

    CMD_DB_DAY7_KILLBOSS_DATA_INIT = 14018,             //GS-DB 7天活动boss 突击
    CMD_DB_DAY7_KILLBOSS_DATA_UPDATE = 14019,             //GS-DB 更新7天boss突击

    CMD_DB_GM_COMMAND = 14020,//GS-DB GM命令

    CMD_DB_UPDATE_KILLROLE = 14021,

    CMD_DB_GET_FAMILYFULI_INFO = 14022,// GS-DB 查询是否可以领取礼包
    CMD_DB_GET_FAMILYFULI = 14023, // GS-DB 国王帮会福利礼包

    CMD_DB_GET_DAILY_BUY_LIMIT_INFO = 14024, // GS-DB 获取每日限购数据

    CMD_DB_ADD_ELEMENT_HEART = 14025,//添加一个元素之心
    CMD_DB_UPDATE_ELEMENT_HEART = 14026,//添加一个元素之心
    CMD_DB_DEL_ELEMENT_HEART = 14027,//添加一个元素之心
    CMD_DB_UPDATE_ELEMENT_REFINE = 14028,//更新元素之心提炼数据

    CMD_DB_UPDATE_JINGLING = 14029,//更新精灵数据提炼数据

    CMD_DB_QUERY_WSXIANMAIDATA_BY_ROLEID = 14030,//获取角色仙脉重铸数据 [2016-04-27 zhanglin]

    CMD_DB_ADDORUPDATE_XIANMAICHONGZHU_DATA = 14031,//更新或者重铸仙脉数据 [2016-04-27 zhanglin]

    CMD_DB_UPDATE_SCHOOL_DATA = 14032,//更新师徒数据

    CMD_DB_ADD_YUEKA_DATA = 14033,//获得月卡
    CMD_DB_UPDATE_YUEKA_DATA = 14034,//更新月卡

    CMD_DB_GETUSER_RECHARGEPOINTMALL_DATA = 14035,//从DB中获取账号积分商城的数据

    CMD_DB_QUERY_USER_RECHARGE_POINT = 14036,//从DB中获取充值积分

    CMD_DB_UPDATE_USER_RECHARGE_POINT = 14037,//更新用户的充值积分

    CMD_DB_UPDATE_USER_RECHARGEPOINTMALL_DATA = 14038,//更新用户积分商城的购买次数

    CMD_DB_QUERY_AND_INITIALIZE_HOLEDATA = 14039,//查询或者初始化装备部位孔信息

    CMD_DB_UPDATE_OR_ADD_JEWELHOLE = 14040,//更新或者添加装备打孔数据

    CMD_DB_OFFLINE_GMCOMMAND = 15000,//GM操作离线玩家[2016-2-27 zhanglin]

    CMD_DB_GET_KUAFU_CITY_NAME = 15001,//通过CITYID获取跨服城池名字

    CMD_LOGDB_ADD_ITEM_LOG = 20000,             // 向日志数据库服务器添加物品操作日志
    CMD_LOGDB_BUY_ITEM_LOG = 20002,             // 向日志数据库服务器购买物品操作日志

    CMD_DB_ERR_RETURN = 32767,

    CMD_DB_GM_KUAFU_BATTLE = 20001,           //GM操作跨服战斗       [2016-3-15 zhanglin]
  };

  public enum TCPProcessCmdResults { RESULT_OK = 0, RESULT_FAILED = 1, RESULT_DATA = 2 };


  public enum TaskClasses
  {
    MainTask = 0,       //主线
    SpecialTask = 2,        //也是一种循环任务？
    CircleTaskStart = 3, //环式任务开始
    LieshaTask = 3,     //猎杀日常
    WuxueTask = 4,      //武学日常
    JungongTask = 5,    //军功日常
    MozuTask = 6,       //魔族帮会
    BanghuiTask = 7,        //帮会任务
    DailyTask = 8,      //日常任务
    XianMaiDailyTask = 9, //仙脉日常任务
    CircleTaskEnd = 10,   //环式任务结束
  }

}