//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: WSRechargePointMallData.proto
namespace Server.Data
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"WSRechargePointMallItem")]
    public partial class WSRechargePointMallItem : global::ProtoBuf.IExtensible
    {
        public WSRechargePointMallItem() { }


        private string _ID = "";
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"ID", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ID
        {
            get { return _ID; }
            set { _ID = value; }
        }

        private string _LeftTimes = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"LeftTimes", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string LeftTimes
        {
            get { return _LeftTimes; }
            set { _LeftTimes = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"WSRechargePointMallData")]
    public partial class WSRechargePointMallData : global::ProtoBuf.IExtensible
    {
        public WSRechargePointMallData() { }


        private string _RechargePoint = "";
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"RechargePoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string RechargePoint
        {
            get { return _RechargePoint; }
            set { _RechargePoint = value; }
        }

        private string _ErrorCode = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"ErrorCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ErrorCode
        {
            get { return _ErrorCode; }
            set { _ErrorCode = value; }
        }
        private readonly global::System.Collections.Generic.List<Server.Data.WSRechargePointMallItem> _Items = new global::System.Collections.Generic.List<Server.Data.WSRechargePointMallItem>();
        [global::ProtoBuf.ProtoMember(3, Name = @"Items", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Server.Data.WSRechargePointMallItem> Items
        {
            get { return _Items; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

}