//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TimeLimitPanicBuyingData.proto
namespace Server.Data
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ABuyGoodsNumber")]
    public partial class ABuyGoodsNumber : global::ProtoBuf.IExtensible
    {
        public ABuyGoodsNumber() { }


        private string _ID = "";
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"ID", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ID
        {
            get { return _ID; }
            set { _ID = value; }
        }

        private string _All_ReMain = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"All_ReMain", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string All_ReMain
        {
            get { return _All_ReMain; }
            set { _All_ReMain = value; }
        }

        private string _Person_ReMainc = "";
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"Person_ReMainc", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Person_ReMainc
        {
            get { return _Person_ReMainc; }
            set { _Person_ReMainc = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"TimeLimitPanicBuyingData")]
    public partial class TimeLimitPanicBuyingData : global::ProtoBuf.IExtensible
    {
        public TimeLimitPanicBuyingData() { }


        private string _Errow = "";
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"Errow", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errow
        {
            get { return _Errow; }
            set { _Errow = value; }
        }
        private readonly global::System.Collections.Generic.List<Server.Data.ABuyGoodsNumber> _NumberList = new global::System.Collections.Generic.List<Server.Data.ABuyGoodsNumber>();
        [global::ProtoBuf.ProtoMember(2, Name = @"NumberList", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Server.Data.ABuyGoodsNumber> NumberList
        {
            get { return _NumberList; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

}